version: "3.9"  # optional since v1.27.0

services:
  
  fhir-mapper:
    build: ./fhir-mapper
    container_name: fhir-mapper
    restart: always
    environment:
      - APP_NAME=fhir-mapper
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: fhir-mapper.logging

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - ${PORT}:80
    volumes:
    - serverlogs:/var/log/nginx
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.logging

  fluentd:
    container_name: fluentd
    user: root
    build: ./fluentd
    image: fluentd
    volumes:
    # - ./logs:/output/ 
    - serverlogs:/output/
    logging:
      driver: "local"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

volumes:
  serverlogs:
    driver: local