version: "3.9"  # optional since v1.27.0

services:
  
  fhir-mapper:
    build: ./fhir-mapper
    container_name: fhir-mapper
    restart: always
    environment:
      - APP_NAME=fhir-mapper
    #expose:
    #  - 8080
    volumes:
      - fhir-mapper-log:/fhir-mapper

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - ${PORT}:80

volumes:
  fhir-mapper-log:
    driver: local